import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { FaTimes } from "react-icons/fa"
import {useSession, signIn, signOut} from "next-auth/react"
import { ChangeEvent, useState} from "react"
import SearchBar from '../../components/dashboard/SearchBar'

export default function dashboard() {

  const [searchToggle, useSearchToggle] = useState(false)
  const handleSearchToggle = () => {
    useSearchToggle(prev => !prev)
    return true
  }


return (
<>
<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="border-2 border-teal-500 flex-col w-screen h-full min-h-screen bg-slate-300">
        <SearchBar />
      </main>


</>
  )
}
